import parse_files as pf
import os


def parse_html(current_dir=os.getcwd()) -> str:
    """
    Automatically parses the newest html file that was generated by the CISCAT
        Assessor tool

    Params:
    current_dir(str): working directory (should always be this)

    Returns:
    str: the file information grabbed from the read() function
    """
    html_filename = ""
    try:
        html_filename = get_newest_html(current_dir)
    except FileNotFoundError as fnfe:
        print(fnfe)

    # read in html code
    with open(html_filename, 'r', encoding='utf-8') as html_report:
        html_file_data = html_report.read()

    # -- we now have the html code -- #
    return html_file_data


def get_newest_html(current_dir=os.getcwd()):
    """
    Gets the filename of the most recent html file with the current directory'

    Params:
    current_dir(str): should always be your working directory

    Returns:
    str: filename of most recent html file
    """
    curr_dir_files = pf.get_curr_files(current_dir)
    html_files = [file for file in curr_dir_files if file.endswith('.html')]
    if len(html_files) == 0:
        raise FileNotFoundError("ERR: there are no HTML files in your working directory")
    return html_files[-1]


parse_html()
